name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

permissions:
  id-token: write
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}
        role-session-name: GitHub-OIDC-gda-backup
    - name: Install diesel
      run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/diesel-rs/diesel/releases/download/v2.2.0/diesel_cli-installer.sh | sh
    - name: Initialize database
      run: diesel migration run --database-url postgres://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost/postgres
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - name: List files
      run: ls . -R
    - name: Prepare release
      run: |
        mkdir -p ./release
        cp ./target/release/gda_backup ./release/gda_backup
        cp ./diesel.toml ./release/diesel.toml
        cp -r ./migrations ./release/migrations
    - name: List files
      run: ls migrations/ -R
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r dir.zip dir
    - name: Deploy release
      uses: ncipollo/release-action@v1
      #if: ${{ github.event_name != 'pull_request' }}
      with:
        artifacts: "target/release/gda_backup,diesel.toml,migrations/*"
        body: "Test release"
        name: test
        tag: 0.0.1
