name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Install diesel
      run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/diesel-rs/diesel/releases/download/v2.2.0/diesel_cli-installer.sh | sh
    - name: Start database
      uses: hoverkraft-tech/compose-action@v2.0.0
      with:
        compose-file: ./tests/docker-compose.yml
    - name: Initialize database
      run: diesel migration run --config file ./tests/.env
    - name: Run tests
      run: cargo test --verbose
